#!/bin/bash

echo "Installing dependencies"
sudo apt-get install -y checkinstall
sudo apt-get install -y  python-dev python3-dev ruby ruby-dev
sudo apt-get install -y libx11-dev libxt-dev libgtk2.0-dev libncurses5 ncurses-dev

cd ~
git clone https://github.com/vim/vim.git

cd vim
./configure \
--enable-perlinterp \
--enable-python3interp \
--enable-rubyinterp \
--enable-cscope \
--enable-gui=auto \
--enable-gtk2-check \
--enable-gnome-check \
--with-features=huge \
--enable-multibyte \
--with-x \
--with-compiledby="xorpd" \
--with-python3-config-dir=/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu \
--prefix=/opt/vim74

echo "Making"
make

echo "Building test"
make test

sudo checkinstall 

sudo mv /usr/bin/vi /usr/bin/vi.BKP > /dev/null
sudo mv /usr/bin/vim /usr/bin/vim.BKP > /dev/null

sudo ln -s /opt/vim74/bin/vim /usr/bin/vim
sudo ln -s /opt/vim74/bin/vim /usr/bin/vi
