#!/bin/bash

# ==================================================
# Dotfiles Setup
# =================================================

DIR="$( cd ../dotFiles && pwd )"
# Create links to dotfiles
echo "Creating dotfile softlinks"
cd ~

# Backup existing files in order to be able to add links
mv .vimrc .vimrc.BKP 
mv .bashrc .bashrc.BKP
mv .zshrc .zshrc.BKP
mv .tmux.conf .tmux.conf.BKP

ln -s $DIR/.vimrc .vimrc
ln -s $DIR/.bashrc .bashrc
ln -s $DIR/.zshrc .zshrc
ln -s $DIR/.tmux.conf .tmux.conf
