#!/bin/bash


# stop on first error
set -e
# Add i3 repository to sources.list
echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" | sudo tee --append /etc/apt/sources.list

# update sources and install

sudo apt-get update
sudo apt-get --allow-unauthenticated install sur5r-keyring
sudo apt-get update
sudo apt-get install -y i3
sudo apt-get install -y feh compton rofi

# set dofile links
ln -s ~/Projects/configFiles/dotFiles/i3 ~/.config/i3
ln -s ~/Projects/configFiles/dotFiles/i3status ~/.config/i3status
ln -s ~/Projects/configFiles/dotFiles/.compton.conf ~/.compton.conf
