#!/bin/bash

set -e
# Add repositories needed
echo "Adding Repositories..." 

sudo sudo add-apt-repository -y ppa:videolan/stable-daily
sudo add-apt-repository -y ppa:fkrull/deadsnakes
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo add-apt-repository -y ppa:gnome3-team/gnome3
sudo add-apt-repository -y ppa:webupd8team/java
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager

# Update the repos
sudo apt-get update

# Install updates
sudo apt-get -y  upgrade
sudo apt-get -y dist-upgrade

# Install packages
sudo apt-get install -y git zsh
sudo apt-get install -y python3.5 python-dev python3-dev python-pip python3-pip 
sudo apt-get install -y python3.5-dev build-essential libssl-dev libffi-dev
sudo apt-get install -y synaptic vlc 
#sudo apt-get install -y gimp gimp-data gimp-plugin-registry gimp-data-extras
sudo apt-get install -y y-ppa-manager bleachbit
sudo apt-get install -y openjdk-7-jre oracle-java8-installer 
#sudo apt-get install -y flashplugin-installer 
sudo apt-get install -y unace unrar zip unzip p7zip-full p7zip-rar sharutils rar 
sudo apt-get install -y uudeview mpack arj cabextract file-roller 
sudo apt-get install -y libxine1-ffmpeg mencoder flac faac faad sox ffmpeg2theora libmpeg2-4 uudeview libmpeg3-1 mpeg3-utils mpegdemux liba52-dev mpeg2dec 
sudo apt-get install -y vorbis-tools id3v2 mpg321 mpg123 libflac++6 totem-mozilla icedax lame libmad0 libjpeg-progs libdvdcss2 libdvdread4 libdvdnav4 libswscale-extra-2
sudo apt-get install -y ubuntu-restricted-extras 
# Install tmux
sudo apt-get install -y tmux
sudo apt-get install -y htop
sudo apt-get install -y vim

# echo "Install DVD Stuff"
# # Take care of encrypted DVDs
# ./installDVDStuff

echo "Install Chrome Browser"
#Install Chrome
./installChrome

# Install Oh-My-Zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
