#!/bin/bash

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Powerline Fonts
cd ~ 
wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mkdir ~/.fonts
mv PowerlineSymbols.otf ~/.fonts/
sudo fc-cache -vf ~/.fonts/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

# Install all Plugins
vim +PluginInstall +qall

# Build and install YCM
sudo apt-get install build-essential cmake python-dev python3-dev python3.5-dev
python3.5 ~/.vim/bundle/YouCompleteMe/install.py

# Install ack for ack.vim
sudo apt-get isntall -y ack-grep
